version: '3.7'
services:
  arangodb_db_container:
    container_name: arangodb_db_container
    image: arangodb:latest
    environment:
      ARANGO_ROOT_PASSWORD: rootpassword
    ports:
      - 8529:8529
    volumes:
      - arangodb_data_container:/var/lib/arangodb3
      - arangodb_apps_data_container:/var/lib/arangodb3-apps
  springboot_app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - arangodb_db_container
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - D:\Projects\test-angular\service-back\src\main\resources\application-docker.properties:/app/config/application.properties
volumes:
  arangodb_data_container:
    external: true
  arangodb_apps_data_container:
    external: true
