server.port=8443
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=map-viewer
server.address=0.0.0.0

arangodb.spring.data.database=spring-demo
arangodb.spring.data.user=root
arangodb.spring.data.password=
# Decommenter pour local
arangodb.spring.data.hosts=localhost:8529
# Decommenter pour local Docker
#arangodb.spring.data.hosts=arangodb_db_container:8529